---
- name: Register raspbian distribution
  # see: https://raspberrypi.stackexchange.com/questions/6974/how-can-i-determine-which-os-image-i-am-running#40826
  shell: cat /etc/os-release | grep ID=raspbian
  when: ansible_os_family == "Debian"
  ignore_errors: true
  register: _os_release_id
  changed_when: false
  failed_when: false

- name: Set _os_is_raspbian according to findings in prior task
  set_fact: 
    _os_is_raspbian: "{{ _os_release_id['stdout'] | regex_findall('raspbian') | list | length > 0 }}"

- debug:
    var: _os_is_raspbian

- name: Set network interface profiles and static IP
  include_tasks: 
    file: debian/networking-configure-interfaces.yml
  vars:
    _interface_profiles: "{{ networking_interface_profiles | mandatory }}"
    _interfaces: "{{ networking_device_interfaces }}"
  when: >
    ansible_os_family == "Debian"
    and 'interfaces' in subtasks

- name: Set Hostname
  include_tasks: 
    file: debian/networking-set-hostname.yml
  vars:
    _domain: "{{ networking_group_domain | mandatory }}"
    _interfaces: "{{ networking_device_interfaces }}"
    _host_group: "{{ networking_group }}"
  when: >
    ansible_os_family == "Debian"
    and 'hostname' in subtasks

- name: Set netfilter and iptables definitions
  include_tasks: 
    file: debian/networking-netfilter.yml
  vars:
    _iptables_definitions: "{{ networking_iptables_definitions | mandatory }}"
  when: >
    ansible_os_family == "Debian"
    and 'netfilter' in subtasks

- debug:
    msg: "{{ item }}"
  with_items:
    - "hostname status: {{ _hostname | default('None') }}"
    - "hostsfile status: {{ _hostsfile | default('None') }}"
    - "network interfaces status: {{ _interface_profiles_status | default('None') }}"

- name: Reboot and wait for connection
  reboot:
    pre_reboot_delay: 5
    post_reboot_delay: 10
  when: >
    'interfaces' not in subtasks
    and (
      (_hostname['changed']|default(false))
      or (_hostsfile['changed']|default(false))
    )

- name: Reboot and continue
  shell: sleep 5 && reboot
  async: 1
  poll: 0
  register: _reboot
  notify: [ 'wait for reboot' ]
  when: >
    'interfaces' in subtasks
    and (_interface_profiles_status['changed']|default(false))
