---
- name: Configure Netplan # (On Ubuntu only; other systems use most likely ifupdown)
  template: 
    src: netplan/50-cloud-init.yaml.j2
    dest: /etc/netplan/50-cloud-init.yaml
    owner: root
    group: root
    mode: 0755
  register: _interface_profiles_status

- name: Apply changes on Netplan
  command: netplan apply
  when: _interface_profiles_status['changed']
