---
- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  when: >
    not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
    or not inventory_hostname == ansible_hostname
  register: _hostname

- name: Ensure all devices are listed in /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    backup: true
  register: _hostsfile
